// Generated by CoffeeScript 1.3.1
(function() {

  window.onload = function() {
    var currentTrack, el, models, player, sp;
    sp = getSpotifyApi(1);
    models = sp.require("sp://import/scripts/api/models");
    player = models.player;
    currentTrack = player.track;
    el = document.getElementById('np');
    if (currentTrack != null) {
      return el.innterHTML = "Currently shipping to " + currentTrack;
    }
  };

}).call(this);
